[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "world-codespaces-api-services"
version = "0.1.0"
dependencies = [
    "pennant"
]

readme = "README.md"
description = "Server-sided API interaction installed to Codespaces container."
