name: Publish release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Setup Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.12
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install --only-upgrade python3-pip
          sudo python -m pip install -r docs/requirements.txt
          sudo cd docs && make html
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      needs: publish
      step:
        - name: Deploy Github Pages
          id: deployment
          uses: actions/deploy-pages@v4.0.5
